name: Build Bazel Targets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        os: [ ubuntu-latest , macOS-latest , windows-latest ]
    #        include:
    #          - os: macOS-latest
    #            arch: arm64

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      #      - name: Cache bazel
      #        uses: actions/cache@v2
      #        env:
      #          cache-name: bazel-cache
      #        with:
      #          path: |
      #            /home/runner/.cache/bazel
      #            /home/runner/.cache/bazelisk
      #          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: lowercase runner.os
        run: |
          echo "RUNNER_OS_LOW=$(echo ${RUNNER_OS} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        #          echo "RUNNER_OS_LOW=${RUNNER_OS,,}" >> $GITHUB_ENV


        env:
          RUNNER_OS: ${{ runner.os }}
        shell: bash

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.cache/bazel
            /home/runner/.cache/bazelisk
          key: bazel-${{ env.RUNNER_OS_LOW }}-${{ hashFiles('**/*.bzl', '**/*.BUILD') }}

      #      - name: Install LLVM and Check Version (macOS)
      #        if: runner.os == 'macOS'
      #        run: |
      #          # echo 'CC=$(brew --prefix llvm@15)/bin/clang' >> $GITHUB_ENV
      #          # echo 'CXX=$(brew --prefix llvm@15)/bin/clang++' >> $GITHUB_ENV
      #
      #          brew install llvm
      #          ls -l /usr/local/opt/llvm/bin
      #          ls -l /usr/local/opt/llvm/lib
      #          echo 'LDFLAGS="-L/usr/local/opt/llvm/lib"' >> $GITHUB_ENV
      #          echo 'CPPFLAGS="-I/usr/local/opt/llvm/include"' >> $GITHUB_ENV
      #          echo 'CC=/usr/local/opt/llvm/bin/clang' >> $GITHUB_ENV
      #          echo 'CXX=/usr/local/opt/llvm/bin/clang++' >> $GITHUB_ENV
      #
      #        shell: bash
      - name: Install LLVM and Check Version (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm
          echo "LLVM_PATH=/usr/local/opt/llvm" >> $GITHUB_ENV
          echo 'LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"' >> $GITHUB_ENV
          echo 'CPPFLAGS="-I/usr/local/opt/llvm/include"' >> $GITHUB_ENV
          echo 'CC=/usr/local/opt/llvm/bin/clang' >> $GITHUB_ENV
          echo 'CXX=/usr/local/opt/llvm/bin/clang++' >> $GITHUB_ENV
          echo 'LIBRARY_PATH="/usr/local/opt/llvm/lib/c++:$LIBRARY_PATH"' >> $GITHUB_ENV
        shell: bash

      #      - name: Mount bazel cache
      #        uses: actions/cache@v3
      #        with:
      #          path: "/home/runner/.cache/bazel"
      #          key: bazel

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1.12.1
      #        with:
      #          vsversion: 2019
      #          toolset: 14.XX

      - name: List MSVC dirs
        if: runner.os == 'Windows'
        run: |
          ls -l "${{ env.VCPKG_ROOT }}"
          ls -l "${{ env.VCINSTALLDIR }}"
          ls -l "${{ env.VCToolsInstallDir }}"
          ls -l "${{ env.VCToolsInstallDir }}/bin/HostX64/x64"

      #  Visual C++ build tools seems to be installed at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC
      #But Bazel can't find the following tools:
      #  VCVARSALL.BAT, cl.exe, link.exe, lib.exe, ml64.exe
      #  for x64 target architecture



      #      - name: Get bazel cache directory path
      #        id: bazel-cache-dir-path
      #        run: echo "dir=~/.cache/bazel" >> $GITHUB_OUTPUT
      #
      #      - name: Cache bazel modules
      #        id: cache-bazel
      #        uses: actions/cache@v3
      #        env:
      #          cache-name: cache-bazel-modules
      #        with:
      #          path: ${{ steps.bazel-cache-dir-path.outputs.dir }}
      #          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/WORKSPACE.bazel') }}
      #          restore-keys: |
      #            ${{ runner.os }}-build-${{ env.cache-name }}-
      #            ${{ runner.os }}-build-
      #            ${{ runner.os }}-
      #Found with vswhere: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
      #      - name: List the state of bazel cache
      #        if: steps.cache-bazel.outputs.cache-hit != 'true'
      #        continue-on-error: true
      #        run: ls ~/.cache/bazel


      - name: Find MSVC tools (Windows)
        if: runner.os == 'Windows'
        run: |
          which cl
          which link
          which lib
          which ml64

#      - name: Check Perl
#        run: |
#          perl -v
#          which perl
#        shell: pwsh
#
#      - name: Check Perl
#        run: |
#          perl -v
#          which perl
#        shell: bash

#      - name: Update PATH
#        run: |
#          echo "PATH=C:/Strawberry/perl/bin;$env:PATH" >> $env:GITHUB_ENV
#        shell: pwsh

#      - name: Install Perl module Pod::Usage (Windows)
#        if: runner.os == 'Windows'
#        run: |
#          cpan Pod::Usage
#          ls "C:\STRAWB~1\perl\site\lib\Pod"
#          ls "C:\STRAWB~1\perl\lib"
#          ls "C:\Strawberry\perl\site\lib\Pod"
#          ls "C:\Strawberry\perl\lib"
#        shell: pwsh

#      - name: Update PERL5LIB
#        if: runner.os == 'Windows'
#        run: |
#          echo "PERL5LIB=C:/Strawberry/perl/site/lib;C:/Strawberry/perl/site/lib/Pod;C:/Strawberry/perl/vendor/lib;C:/Strawberry/perl/vendor/lib/Pod;$PERL5LIB" >> $GITHUB_ENV
#        shell: bash

      #  brew install libomp

      #      - name: Install Perl module Pod::Usage (Windows)
      #        if: runner.os == 'Windows'
      #        run: |
      #          cpan Pod::Usage
      #          $output = perl -V:installsitelib
      #          $output -match "'.*'"
      #          $PERL5LIB = $matches[0] -replace "'"
      #          echo "PERL5LIB=$PERL5LIB" >> $GITHUB_ENV
      #        shell: pwsh

      #      - name: Debug Perl
      #        if: runner.os == 'Windows'
      #        shell: pwsh
      #        run: |
      #          perl -E 'say for @INC'
      #          perl -E 'use Pod::Usage; say $INC{"Pod/Usage.pm"}'

      #      - name: Prepare Bazel (Windows)
      #        if: runner.os == 'Windows'
      #        run: |
      #          curl -LO "https://github.com/redsun82/bazel/releases/download/vs-2022-fix-0.1/bazel-vs2022.exe"
      #          echo "PATH=$PATH:$(pwd)" >> $GITHUB_ENV
      #        shell: bash

      #      - name: Build Bazel Target
      #        env:
      #          RUNNER_OS: ${{ runner.os }}
      #        shell: bash
      #        run: |
      #          if [[ "${RUNNER_OS}" == "Windows" ]]; then
      #            bazel-vs2022 build @pydin//:pydin-zip
      #              --action_env=BAZEL_VC=${{ env.VCINSTALLDIR }}
      #              --action_env=BAZEL_VC_FULL_VERSION=${{ env.VCToolsVersion }}
      #          else
      #            # Add commands for other OS types here
      #            bazel build @pydin//:pydin-tar
      #          fi
      #      - name: Build Bazel Target (Windows)
      #        if: runner.os == 'Windows'
      #        shell: pwsh
      #        run: |
      #          bazel-vs2022 build @pydin//:pydin-zip `
      #            --action_env=BAZEL_VC=${{ env.VCINSTALLDIR }} `
      #            --action_env=BAZEL_VC_FULL_VERSION=${{ env.VCToolsVersion }}

      #      - name: Build Bazel Target (Windows)
      #        if: runner.os == 'Windows'
      #        shell: pwsh
      #        run: |
      #          curl -LO "https://github.com/redsun82/bazel/releases/download/vs-2022-fix-0.1/bazel-vs2022.exe"
      #          $env:PATH += ";$pwd"
      #          ./bazel-vs2022 build @pydin//:pydin-zip `
      #            --action_env=BAZEL_VC=${{ env.VCINSTALLDIR }} `
      #            --action_env=BAZEL_VC_FULL_VERSION=${{ env.VCToolsVersion }}

      #      - name: Setup PkgConfig (Windows)
      #        if: runner.os == 'Windows'
      #        env:
      #          PKG_CONFIG_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip"
      #          GETTEXT_RUNTIME_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip"
      #          GLIB_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip"
      #        run: |
      #          curl -LO "${{ env.PKG_CONFIG_ZIP }}"
      #          7z x pkg-config_0.26-1_win32.zip -oC:\MinGW\bin pkg-config.exe
      #          curl -LO "${{ env.GETTEXT_RUNTIME_ZIP }}"
      #          7z x gettext-runtime_0.18.1.1-2_win32.zip -oC:\MinGW\bin intl.dll
      #          curl -LO "${{ env.GLIB_ZIP }}"
      #          7z x glib_2.28.8-1_win32.zip -oC:\MinGW\bin libglib-2.0-0.dll
      #          echo "C:\MinGW\bin" >> $GITHUB_PATH
      #          echo "PKG_CONFIG_EXECUTABLE=C:\MinGW\bin\pkg-config.exe" >> $GITHUB_ENV
      #        shell: pwsh
      #      - name: Set up Clang (windows)
      #        uses: egor-tensin/setup-clang@v1
      #        with:
      #          version: latest
      #          platform: x64

      - name: Print LLVM location (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "LLVM location: $(which clang)"
          echo "LLVM config location: $(which llvm-config)"
        shell: bash

      - name: Add clang path to $PATH env (Windows)
        shell: bash
        if: runner.os == 'Windows'
        run: |
          echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
          echo "BAZEL_LLVM=C:\msys64\mingw64\bin" >> $GITHUB_ENV

      - name: Build Bazel Target (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          curl -LO "https://github.com/redsun82/bazel/releases/download/vs-2022-fix-0.1/bazel-vs2022.exe"
          chmod +x ./bazel-vs2022.exe
          ./bazel-vs2022.exe build @pydin//:pydin-zip \
            --compiler=clang-cl \
            --action_env=BAZEL_LLVM=${{ env.BAZEL_LLVM }}


#      - name: Build Bazel Target (Windows) MSVC
#        if: runner.os == 'Windows'
#        shell: pwsh
#        run: |
#          curl -LO "https://github.com/redsun82/bazel/releases/download/vs-2022-fix-0.1/bazel-vs2022.exe"
#          $env:PATH += ";$pwd"
#          $BAZEL_VC = "${{ env.VCINSTALLDIR }}".replace('\', '/')
#          $BAZEL_VC_FULL_VERSION = "${{ env.VCToolsVersion }}".replace('\', '/')
#          $PKG_CONFIG = "${{ env.PKG_CONFIG_EXECUTABLE }}".replace('\', '/')
#          $BAZEL_LLVM = "${{ env.BAZEL_LLVM }}".replace('\', '/')
#          ./bazel-vs2022 build @pydin//:pydin-zip `
#            --action_env=BAZEL_VC=$BAZEL_VC `
#            --action_env=BAZEL_VC_FULL_VERSION=$BAZEL_VC_FULL_VERSION `
#            --action_env=PKG_CONFIG=$PKG_CONFIG `
#            --compiler=clang-cl `
#            --action_env=BAZEL_LLVM=$BAZEL_LLVM `

      - name: Build Bazel Target (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            bazel build @pydin//:pydin-tar --config=unix
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            bazel build @pydin//:pydin-tar \
                --config=unix \
                --action_env=CC=${{ env.CC }} \
                --action_env=CXX=${{ env.CXX }} \
                --action_env=LDFLAGS=${{ env.LDFLAGS }} \
                --action_env=CPPFLAGS=${{ env.CPPFLAGS }} 

          fi



      - name: Extract Pydin version
        run: echo "PYDIN_VERSION=$(cat pydin/VERSION)" >> $GITHUB_ENV
      - name: Print Pydin version
        run: |
          echo "pydin version: $PYDIN_VERSION"

      - name: List files
        run: ls -l bazel-bin/external/pydin/

      - name: lowercase runner.os
        run: |
          echo "RUNNER_OS_LOW=${RUNNER_OS,,}" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pydin-${{ env.PYDIN_VERSION }}-${{ env.RUNNER_OS_LOW }}-build${{ github.run_number }}
          path: |
            bazel-bin/external/pydin/pydin.tar.gz
            bazel-bin/external/pydin/pydin.zip

      - name: Setup QEMU
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        if: matrix.arch == 'arm64'
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        if: matrix.arch == 'arm64'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
      - name: Run Docker Image
        if: matrix.arch == 'arm64'
        run: docker run -v $(pwd):/app -w /app geoffreygarrett/bor:latest bazel build @pydin//:pydin-tar

      - name: Adjust permissions for Bazel cache
        run: chmod -R 777 "/home/runner/.cache/bazel"
        shell: bash