name: Build Bazel Targets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        include:
          - os: macOS-latest
            arch: arm64

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Build Bazel Target
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "Windows build"
            bazel build @pydin//:pydin-zip \
              --action_env=BAZEL_VC=${{ env.VCINSTALLDIR }} \
              --action_env=INCLUDE=${{ env.INCLUDE }} \
              --action_env=BAZEL_VC_FULL_VERSION=${{ env.VCToolsVersion }}
          else
            # Add commands for other OS types here
            echo "Non-Windows build"
            bazel build @pydin//:pydin-tar
          fi
        shell: bash
      - name: Extract Pydin version
        run: echo "PYDIN_VERSION=$(cat pydin/VERSION)" >> $GITHUB_ENV
      - name: Print Pydin version
        run: |
          echo "pydin version: $PYDIN_VERSION"
      - name: List files
        run: ls -l bazel-bin/external/pydin/

      - name: lowercase runner.os
        run: |
          echo "RUNNER_OS=${RUNNER_OS,,}" >> $GITHUB_ENV
        env:
          RUNNER_OS: ${{ runner.os }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pydin-${{ env.RUNNER_OS }}-${{ env.PYDIN_VERSION }}-build${{ github.run_number }}
          path: |
            bazel-bin/external/pydin/pydin.tar.gz
            bazel-bin/external/pydin/pydin.zip

      - name: Setup QEMU
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        if: matrix.arch == 'arm64'
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        if: matrix.arch == 'arm64'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
      - name: Run Docker Image
        if: matrix.arch == 'arm64'
        run: docker run -v $(pwd):/app -w /app geoffreygarrett/bor:latest bazel build @pydin//:pydin-tar

