name: Bazel Steward

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Bazel steward
        uses: VirtusLab/bazel-steward@v1.0.0